### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by ArturitoDeveloper** [freddxvill/Download-platzi#6]
Seguí los pasos pero me muestra el siguiente error.

Iniciando ...

Traceback (most recent call last):
  File "E:\Projects\Download-platzi\platzi.py", line 116, in <module>
    links = list_links(url_curso, url_pag)
  File "E:\Projects\Download-platzi\platzi.py", line 25, in list_links
    links = s_curso.find('div', attrs={'class':'Content-feed'}).find_all('div', attrs={'class':'ContentClass'})
AttributeError: 'NoneType' object has no attribute 'find_all'

Por favor, Podrias ayudarme?

Estaré pendiente de tu respuesta

**Comment by freddxvill** [comment]
Hola, esto puede ser debido a que se cambio la interfaz de usuario y no logra encontrar las rutas de los elementos . Habria que actualizar la busqueda que se realiza con BeautifulSoup.

**Comment by DanHermes-Devs** [comment]
@freddxvill haz podido realizar lo que comentas? por que justo como cambio la interface de platzi, no funciona el codigo ahora :c
